# Generated by Django 4.0.5 on 2022-06-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Account name')),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Initial balance')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('transaction_type', models.SmallIntegerField(choices=[(1, 'IN'), (2, 'OUT')], verbose_name='Transaction type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.accounts')),
            ],
        ),
    ]
